### PR TITLE
WIP: Added intro.

### PR DESCRIPTION
**Pull request by praveenscience**
@pavinthan Just wanted your quick review on the style of writing here. Let me know if this works. I have completed the whole page, but just wanted to know if this suits. 😇

### CODE REVIEW

**Comment by pavinthan** [comment]
@praveenscience It's really good work 

suggestion: please don't be more literately and use most common words because It's easy to understand by all.

thanks 😄

**Comment by Panchatcharam** [comment]
I second the idea to use the common words and it would be easy for the learners to get more info or get clarification from the community if they use common words.

**Comment by sathyatvrcbe** [comment]
Hello. I am taking up the translation of `golang` to Tamil. It is in progress. He we are translating react to tamil. Why don't we join hands and work as a community. I think with co-ordinated efforts of a community of like-minded people, we can achieve more.

**Comment by pavinthan** [comment]
@sathyatvrcb we happy to work together 🤝 please let us know you plan

**Comment by pavinthan** [comment]
@praveenscience I'm closing this PR because no activities so far, please feel free to create new

**Comment by praveenscience** [comment]
@pavinthan Will do it ASAP. Thanks! 😊

**Pull request closed without merging**
